/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.paul.sourabh;

import javax.swing.JOptionPane;

/**
 *
 * @author soura
 */
public class Assignment1 extends javax.swing.JFrame {

    /**
     * Creates new form Assignment1
     */
    public Assignment1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblKM = new javax.swing.JLabel();
        tfKM = new javax.swing.JTextField();
        lblKM1 = new javax.swing.JLabel();
        tfConvert = new javax.swing.JTextField();
        rbtnMilimeter = new javax.swing.JRadioButton();
        rbtnMeter = new javax.swing.JRadioButton();
        rbtnCentimeter = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversion");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblKM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblKM.setForeground(new java.awt.Color(255, 255, 255));
        lblKM.setText("Enter Value in KM:");

        tfKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKMActionPerformed(evt);
            }
        });

        lblKM1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblKM1.setForeground(new java.awt.Color(255, 255, 255));
        lblKM1.setText("After Conversion:");

        tfConvert.setEditable(false);
        tfConvert.setRequestFocusEnabled(false);
        tfConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfConvertActionPerformed(evt);
            }
        });

        rbtnMilimeter.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnMilimeter);
        rbtnMilimeter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnMilimeter.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMilimeter.setText("Milimeter");
        rbtnMilimeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMeterActionPerformed(evt);
            }
        });

        rbtnMeter.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnMeter);
        rbtnMeter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnMeter.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMeter.setText("Meter");
        rbtnMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMeterActionPerformed(evt);
            }
        });

        rbtnCentimeter.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnCentimeter);
        rbtnCentimeter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnCentimeter.setForeground(new java.awt.Color(255, 255, 255));
        rbtnCentimeter.setText("Centimeter");
        rbtnCentimeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMeterActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(0, 0, 0));
        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(rbtnMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(rbtnCentimeter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnMilimeter, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblKM1)
                                .addGap(28, 28, 28)
                                .addComponent(tfConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblKM)
                                .addGap(18, 18, 18)
                                .addComponent(tfKM, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKM1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMeter)
                    .addComponent(rbtnCentimeter)
                    .addComponent(rbtnMilimeter))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfConvertActionPerformed
    }//GEN-LAST:event_tfConvertActionPerformed

    private void tfKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKMActionPerformed
    }//GEN-LAST:event_tfKMActionPerformed

    private void rbtnMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMeterActionPerformed
       try{
        if(evt.getSource()==rbtnMeter)
            tfConvert.setText(String.valueOf(Integer.parseInt(tfKM.getText())*1000));
        else if(evt.getSource()==rbtnCentimeter)
            tfConvert.setText(String.valueOf(Integer.parseInt(tfKM.getText())*100000));
        else
            tfConvert.setText(String.valueOf(Integer.parseInt(tfKM.getText())*1000000));
       }
       catch(Exception e){
           if(tfKM.getText().isEmpty())
                JOptionPane.showMessageDialog(null, "Text Field should not be Empty!", "Error!", JOptionPane.ERROR_MESSAGE);
           else
               JOptionPane.showMessageDialog(null, "Please input digits only!", "Error!", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_rbtnMeterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfKM.setText("");
        tfConvert.setText("");
        tfKM.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        int opt=JOptionPane.showConfirmDialog(null, "Do you really want to exit?", "Quit", JOptionPane.YES_NO_OPTION);
        if(opt==JOptionPane.YES_NO_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnQuit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKM;
    private javax.swing.JLabel lblKM1;
    private javax.swing.JRadioButton rbtnCentimeter;
    private javax.swing.JRadioButton rbtnMeter;
    private javax.swing.JRadioButton rbtnMilimeter;
    private javax.swing.JTextField tfConvert;
    private javax.swing.JTextField tfKM;
    // End of variables declaration//GEN-END:variables
}
